### ISSUE TITLE
User cannot modify profile or farms when logging in

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-aggregator#19]
This is the error given when logging in with admin@localhost :

```
INFO: ('172.29.0.7', 36666) - "GET /api/v1/users/me HTTP/1.1" 500
backend_1        | ERROR: Exception in ASGI application
backend_1        | Traceback (most recent call last):
backend_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
backend_1        |     result = await asgi(self.receive, self.send)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 125, in asgi
backend_1        |     raise exc from None
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 103, in asgi
backend_1        |     await asgi(receive, _send)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 27, in asgi
backend_1        |     response = await self.dispatch_func(request, self.call_next)
backend_1        |   File "./app/main.py", line 34, in db_session_middleware
backend_1        |     response = await call_next(request)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 44, in call_next
backend_1        |     task.result()
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/middleware/base.py", line 37, in coro
backend_1        |     await inner(request.receive, queue.put)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 74, in app
backend_1        |     raise exc from None
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 63, in app
backend_1        |     await instance(receive, sender)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in awaitable
backend_1        |     response = await func(request)
backend_1        |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 122, in app
backend_1        |     skip_defaults=response_model_skip_defaults,
backend_1        |   File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 54, in serialize_response
backend_1        |     raise ValidationError(errors)
backend_1        | pydantic.error_wrappers.ValidationError: 1 validation error
backend_1        | response
backend_1        |   value is not a valid dict (type=type_error.dict)
```

Seems like be conflicting with newer versions of FastAPI and pydantic

**Comment by mstenta** [comment]
This issue in the FastAPI queue looks similar: https://github.com/tiangolo/fastapi/issues/413

Sounds like there is a solution described over there...

> Setting orm_mode=True in the base model worked as well and looks much better, thank you for the suggestion!

https://github.com/tiangolo/fastapi/issues/413#issuecomment-517492569
