### ISSUE TITLE
Celery worker fails to start

### ISSUE THREAD

**Issue by paul121** [farmOS/farmOS-aggregator#63]
Celery worker isn't starting. I suspect a breaking change from dependencies

```
celeryworker_1   | INFO:__main__:Initializing service
celeryworker_1   | INFO:__main__:Starting call to '__main__.init', this is the 1st time calling it.
celeryworker_1   | INFO:__main__:Service finished initializing
celeryworker_1   | /usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
celeryworker_1   | absolutely not recommended!
celeryworker_1   | 
celeryworker_1   | Please specify a different user using the --uid option.
celeryworker_1   | 
celeryworker_1   | User information: uid=0 euid=0 gid=0 egid=0
celeryworker_1   | 
celeryworker_1   |   uid=uid, euid=euid, gid=gid, egid=egid,
celeryworker_1   | [2020-01-02 19:04:53,879: DEBUG/MainProcess] | Worker: Preparing bootsteps.
celeryworker_1   | [2020-01-02 19:04:53,880: DEBUG/MainProcess] | Worker: Building graph...
celeryworker_1   | [2020-01-02 19:04:53,880: DEBUG/MainProcess] | Worker: New boot order: {Beat, Timer, Hub, Pool, Autoscaler, StateDB, Consumer}
celeryworker_1   | [2020-01-02 19:04:53,885: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
celeryworker_1   | [2020-01-02 19:04:53,886: DEBUG/MainProcess] | Consumer: Building graph...
celeryworker_1   | [2020-01-02 19:04:53,916: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Heart, Mingle, Gossip, Agent, Tasks, Control, event loop}
celeryworker_1   | [2020-01-02 19:04:53,919: DEBUG/MainProcess] | Worker: Starting Hub
celeryworker_1   | [2020-01-02 19:04:53,919: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:53,919: DEBUG/MainProcess] | Worker: Starting Pool
celeryworker_1   | [2020-01-02 19:04:53,953: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:53,953: DEBUG/MainProcess] | Worker: Starting Consumer
celeryworker_1   | [2020-01-02 19:04:53,954: DEBUG/MainProcess] | Consumer: Starting Connection
celeryworker_1   | [2020-01-02 19:04:53,954: ERROR/ForkPoolWorker-1] Process ForkPoolWorker-1
celeryworker_1   | Traceback (most recent call last):
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/billiard/process.py", line 315, in _bootstrap
celeryworker_1   |     handler.createLock()
celeryworker_1   | TypeError: createLock() missing 1 required positional argument: 'self'
celeryworker_1   | [2020-01-02 19:04:53,955: WARNING/ForkPoolWorker-1] Process ForkPoolWorker-1:
celeryworker_1   | [2020-01-02 19:04:53,955: WARNING/ForkPoolWorker-1] Traceback (most recent call last):
celeryworker_1   | [2020-01-02 19:04:53,955: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/site-packages/billiard/process.py", line 315, in _bootstrap
celeryworker_1   |     handler.createLock()
celeryworker_1   | [2020-01-02 19:04:53,955: WARNING/ForkPoolWorker-1] TypeError: createLock() missing 1 required positional argument: 'self'
celeryworker_1   | [2020-01-02 19:04:53,962: DEBUG/MainProcess] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@b4248777ae9c', 'copyright': 'Copyright (c) 2007-2019 Pivotal Software, Inc.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 22.1.8', 'product': 'RabbitMQ', 'version': '3.8.1'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
celeryworker_1   | [2020-01-02 19:04:53,964: INFO/MainProcess] Connected to amqp://guest:**@queue:5672//
celeryworker_1   | [2020-01-02 19:04:53,964: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:53,964: DEBUG/MainProcess] | Consumer: Starting Events
celeryworker_1   | [2020-01-02 19:04:53,970: DEBUG/MainProcess] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@b4248777ae9c', 'copyright': 'Copyright (c) 2007-2019 Pivotal Software, Inc.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 22.1.8', 'product': 'RabbitMQ', 'version': '3.8.1'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
celeryworker_1   | [2020-01-02 19:04:53,972: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:53,972: DEBUG/MainProcess] | Consumer: Starting Heart
celeryworker_1   | [2020-01-02 19:04:53,973: DEBUG/MainProcess] using channel_id: 1
celeryworker_1   | [2020-01-02 19:04:53,974: DEBUG/MainProcess] Channel open
celeryworker_1   | [2020-01-02 19:04:53,974: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:53,974: DEBUG/MainProcess] | Consumer: Starting Mingle
celeryworker_1   | [2020-01-02 19:04:53,975: INFO/MainProcess] mingle: searching for neighbors
celeryworker_1   | [2020-01-02 19:04:53,975: DEBUG/MainProcess] using channel_id: 1
celeryworker_1   | [2020-01-02 19:04:53,978: DEBUG/MainProcess] Channel open
celeryworker_1   | [2020-01-02 19:04:53,989: DEBUG/MainProcess] Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@b4248777ae9c', 'copyright': 'Copyright (c) 2007-2019 Pivotal Software, Inc.', 'information': 'Licensed under the MPL 1.1. Website: https://rabbitmq.com', 'platform': 'Erlang/OTP 22.1.8', 'product': 'RabbitMQ', 'version': '3.8.1'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
celeryworker_1   | [2020-01-02 19:04:53,990: DEBUG/MainProcess] using channel_id: 1
celeryworker_1   | [2020-01-02 19:04:53,991: DEBUG/MainProcess] Channel open
celeryworker_1   | [2020-01-02 19:04:55,005: INFO/MainProcess] mingle: all alone
celeryworker_1   | [2020-01-02 19:04:55,005: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:55,005: DEBUG/MainProcess] | Consumer: Starting Gossip
celeryworker_1   | [2020-01-02 19:04:55,005: DEBUG/MainProcess] using channel_id: 2
celeryworker_1   | [2020-01-02 19:04:55,006: DEBUG/MainProcess] Channel open
celeryworker_1   | [2020-01-02 19:04:55,009: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:55,009: DEBUG/MainProcess] | Consumer: Starting Tasks
celeryworker_1   | [2020-01-02 19:04:55,012: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:55,012: DEBUG/MainProcess] | Consumer: Starting Control
celeryworker_1   | [2020-01-02 19:04:55,012: DEBUG/MainProcess] using channel_id: 3
celeryworker_1   | [2020-01-02 19:04:55,013: DEBUG/MainProcess] Channel open
celeryworker_1   | [2020-01-02 19:04:55,015: DEBUG/MainProcess] ^-- substep ok
celeryworker_1   | [2020-01-02 19:04:55,015: DEBUG/MainProcess] | Consumer: Starting event loop
celeryworker_1   | [2020-01-02 19:04:55,015: DEBUG/MainProcess] | Worker: Hub.register Pool...
celeryworker_1   | [2020-01-02 19:04:55,016: INFO/MainProcess] celery@ab17a5082692 ready.
celeryworker_1   | [2020-01-02 19:04:55,016: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:12 exited with 'exitcode 1'
celeryworker_1   | [2020-01-02 19:04:55,037: CRITICAL/MainProcess] Unrecoverable error: WorkerLostError('Could not start worker processes')
celeryworker_1   | Traceback (most recent call last):
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/worker/worker.py", line 205, in start
celeryworker_1   |     self.blueprint.start(self)
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
celeryworker_1   |     step.start(parent)
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 369, in start
celeryworker_1   |     return self.obj.start()
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
celeryworker_1   |     blueprint.start(self)
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/bootsteps.py", line 119, in start
celeryworker_1   |     step.start(parent)
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
celeryworker_1   |     c.loop(*c.loop_args())
celeryworker_1   |   File "/usr/local/lib/python3.7/site-packages/celery/worker/loops.py", line 59, in asynloop
celeryworker_1   |     raise WorkerLostError('Could not start worker processes')
celeryworker_1   | billiard.exceptions.WorkerLostError: Could not start worker processes
celeryworker_1   | [2020-01-02 19:04:55,039: DEBUG/MainProcess] | Worker: Closing Hub...
celeryworker_1   | [2020-01-02 19:04:55,039: DEBUG/MainProcess] | Worker: Closing Pool...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Worker: Closing Consumer...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Worker: Stopping Consumer...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Consumer: Closing Connection...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Consumer: Closing Events...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Consumer: Closing Heart...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Consumer: Closing Mingle...
celeryworker_1   | [2020-01-02 19:04:55,040: DEBUG/MainProcess] | Consumer: Closing Gossip...
celeryworker_1   | [2020-01-02 19:04:55,041: DEBUG/MainProcess] | Consumer: Closing Tasks...
celeryworker_1   | [2020-01-02 19:04:55,041: DEBUG/MainProcess] | Consumer: Closing Control...
celeryworker_1   | [2020-01-02 19:04:55,041: DEBUG/MainProcess] | Consumer: Closing event loop...
celeryworker_1   | [2020-01-02 19:04:55,041: DEBUG/MainProcess] | Consumer: Stopping event loop...
celeryworker_1   | [2020-01-02 19:04:55,041: DEBUG/MainProcess] | Consumer: Stopping Control...
celeryworker_1   | [2020-01-02 19:04:55,043: DEBUG/MainProcess] Closed channel #3
celeryworker_1   | [2020-01-02 19:04:55,044: DEBUG/MainProcess] | Consumer: Stopping Tasks...
celeryworker_1   | [2020-01-02 19:04:55,044: DEBUG/MainProcess] Canceling task consumer...
celeryworker_1   | [2020-01-02 19:04:55,044: DEBUG/MainProcess] | Consumer: Stopping Gossip...
celeryworker_1   | [2020-01-02 19:04:55,052: DEBUG/MainProcess] Closed channel #2
celeryworker_1   | [2020-01-02 19:04:55,052: DEBUG/MainProcess] | Consumer: Stopping Mingle...
celeryworker_1   | [2020-01-02 19:04:55,052: DEBUG/MainProcess] | Consumer: Stopping Heart...
celeryworker_1   | [2020-01-02 19:04:55,053: DEBUG/MainProcess] | Consumer: Stopping Events...
celeryworker_1   | [2020-01-02 19:04:55,053: DEBUG/MainProcess] | Consumer: Stopping Connection...
celeryworker_1   | [2020-01-02 19:04:55,053: DEBUG/MainProcess] | Worker: Stopping Pool...
celeryworker_1   | [2020-01-02 19:04:55,053: DEBUG/MainProcess] | Worker: Stopping Hub...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] | Consumer: Shutdown Control...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] Canceling task consumer...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] Closing consumer channel...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] | Consumer: Shutdown Heart...
celeryworker_1   | [2020-01-02 19:04:55,054: DEBUG/MainProcess] | Consumer: Shutdown Events...
celeryworker_1   | [2020-01-02 19:04:55,055: DEBUG/MainProcess] Closed channel #1
celeryworker_1   | [2020-01-02 19:04:55,055: DEBUG/MainProcess] | Consumer: Shutdown Connection...
celeryworker_1   | [2020-01-02 19:04:55,056: DEBUG/MainProcess] Closed channel #1
celeryworker_1   | [2020-01-02 19:04:55,056: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
celeryworker_1   |  
celeryworker_1   |  -------------- celery@ab17a5082692 v4.3.0 (rhubarb)
celeryworker_1   | ---- **** ----- 
celeryworker_1   | --- * ***  * -- Linux-4.19.0-6-amd64-x86_64-with-debian-10.1 2020-01-02 19:04:53
celeryworker_1   | -- * - **** --- 
celeryworker_1   | - ** ---------- [config]
celeryworker_1   | - ** ---------- .> app:         worker:0x7f216a133590
celeryworker_1   | - ** ---------- .> transport:   amqp://guest:**@queue:5672//
celeryworker_1   | - ** ---------- .> results:     disabled://
celeryworker_1   | - *** --- * --- .> concurrency: 1 (prefork)
celeryworker_1   | -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
celeryworker_1   | --- ***** ----- 
celeryworker_1   |  -------------- [queues]
celeryworker_1   |                 .> main-queue       exchange=main-queue(direct) key=main-queue
celeryworker_1   |                 
celeryworker_1   | 
celeryworker_1   | [tasks]
celeryworker_1   |   . app.worker.ping_farms
celeryworker_1   |   . celery.accumulate
celeryworker_1   |   . celery.backend_cleanup
celeryworker_1   |   . celery.chain
celeryworker_1   |   . celery.chord
celeryworker_1   |   . celery.chord_unlock
celeryworker_1   |   . celery.chunks
celeryworker_1   |   . celery.group
celeryworker_1   |   . celery.map
celeryworker_1   |   . celery.starmap
celeryworker_1   | 
```

**Comment by paul121** [comment]
The problem is the line `logger.addHandler(logging.NullHandler)` in `backend/app/app/crud/farm.py` (https://github.com/farmOS/farmOS-aggregator/blob/master/backend/app/app/crud/farm.py#L16)

This issue got me here: https://github.com/celery/billiard/issues/223

I'm not quite sure why this is the problem. I used this guide (https://docs.python-guide.org/writing/logging/#logging-in-a-library) to add logging to the Aggregator and farmOS.py. It says "best practice" includes adding a NullHandler, but perhaps this isn't something we should do.

**Comment by paul121** [comment]
Aha! See "Library vs Application Logging: What Is NullHandler?" in https://realpython.com/python-logging-source-code/

> When it comes to logging, there are different best practices in a library versus an app.
...
Firstly, a library logger that is declared with logger = logging.getLogger(__name__) (without any further configuration) will log to sys.stderr by default, even if that’s not what the end user wants. This could be described as an opt-out approach, where the end user of the library has to go in and disable logging to their console if they don’t want it.
...
This leaves it up to the library user, not library developer, to incrementally call methods such as logger.addHandler() or logger.setLevel().

So, in farmOS.py `__init__.py`, we should do this once: `logger.addHandler(logging.NullHandler)` - subsequent files just need `logger = logging.getLogger(__name__)` and they will fall under the top level logger, which will already have the `NullHandler`

But, in the aggregator, we don't want to add the `NullHandler` to any loggers because it is the application generating its own logs, and optionally displaying logs from other libraries (like farmOS.py)

**Comment by paul121** [comment]
To debug this I modified the following line in `backend/app/worker-start.sh` to use a debug log level:
`celery worker -A app.worker -l debug -Q main-queue -c 1 -B`
